### ISSUE TITLE
Add an action to promote to prod

### ISSUE THREAD

**Issue by Afonso-2403** [equinor/isar-robot#94]
**Describe the improvement you would like to see**
Similarly to what is done for other robots, there should be an action to promote isar-robot to prod.
The script can be similar to the one for [isar-taurob](https://github.com/equinor/isar-taurob/actions/runs/6670282431/workflow)

**Comment by tsundvoll** [comment]
We don't actually need isar-robot in Production. Maybe we want an isar-robot in a "real" asset, like Huldra, but then that would be good to have in Staging env.
